#!/bin/bash

echo "🔧 CONFIGURACIÓN AWS CREDENTIALS"
echo "================================"
echo ""
echo "Para continuar con la implementación, necesitas configurar las credenciales de AWS."
echo ""
echo "Ejecuta los siguientes comandos:"
echo ""
echo "1. Configurar AWS CLI:"
echo "   aws configure"
echo ""
echo "2. Proporciona los siguientes datos cuando se soliciten:"
echo "   - AWS Access Key ID: [Tu Access Key]"
echo "   - AWS Secret Access Key: [Tu Secret Key]"
echo "   - Default region name: us-east-1"
echo "   - Default output format: json"
echo ""
echo "3. Verificar configuración:"
echo "   aws sts get-caller-identity"
echo ""
echo "4. Una vez configurado, ejecuta:"
echo "   ./scripts/continue-aws-setup.sh"
echo ""
echo "📋 NOTAS IMPORTANTES:"
echo "- Asegúrate de tener permisos de administrador en tu cuenta AWS"
echo "- El dominio debe estar verificado en Amazon SES"
echo "- Guarda tus credenciales de forma segura"
echo ""